### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by pedroalbanese** [ajaxray/markpdf#10]
As-Salamu Alaikum,

$ go build -ldflags=-s .
# github.com/unidoc/unidoc/pdf/model
C:\Users\0wner\go\src\github.com\unidoc\unidoc\pdf\model\writer.go:538:12: constant 4294967295 overflows int

How do proceed?

Thanks in advance.

**Comment by ajaxray** [comment]
Wa'Alaikum Assalam,

Seem like to be a compatibility issue with unidoc. 
Can you please provide the following details?

- Version of go
- OS details (name and version, 32/64 bit etc.)

**Comment by pedroalbanese** [comment]
I tried with 1.11.13, 1.14.2 and 1.15.3. Windows 7 SP1 32bits.

**Comment by ajaxray** [comment]
The Unidoc version has been fixed by this patch #12 
Now, the dependencies and their versions are specified using go module.

Can you please update and try again?
I am closing the issue now. Please feel free to re-open if the problem exists after updating.
