### ISSUE TITLE
latest release crashes on macos 11.0.1

### ISSUE THREAD

**Issue by coooold** [ajaxray/markpdf#11]
# ./markpdf_darwin-amd64
Killed: 9

**Comment by coooold** [comment]
it may coursed by the old version of upx
repack to solve the problem

https://github.com/coooold/markpdf/releases/tag/1.0.1

**Comment by ajaxray** [comment]
Thanks for the clue 👍🏼 
 
Here is my upx version and it's working well
```
upx 3.96
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

BTW, Closing the issue as resolved.
