### ISSUE TITLE
Add template to text watermark 

### ISSUE THREAD

**Issue by Clouz** [ajaxray/markpdf#13]
Using "text/template" advance text watermark can be improved adding pages numbering function

**Comment by ajaxray** [comment]
Hi @Clouz,

I was thinking, people  generally use fixed-text watermarking. I didn't see this use case before. 
However, I'll check if we can improve the tool with template/placeholder based text.

Thanks a lot for the suggestion! 👍🏼

**Comment by ajaxray** [comment]
Just have seen your PR #14 
Will check it very soon. 
Thanks ❤️

**Comment by ajaxray** [comment]
The feature is included in [this release](https://github.com/ajaxray/markpdf/releases/tag/1.0.1).
