### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by crmarvin42** [ajaxray/markpdf#20]
Maybe I'm missing something, but is there a way to build this for Apple Silicon? I see the Darwin build, but it is not for ARM 64 as far as I can tell. Same goes for the build.sh. No way to build for Darwin + Arm

**Comment by ajaxray** [comment]
Dear friend,

A new build for Mac M1 is added in [this release](https://github.com/ajaxray/markpdf/releases/tag/1.0.1).

Can you please confirm if it's working for you?
