### ISSUE TITLE
File need to be decrypted first

### ISSUE THREAD

**Issue by laraben** [ajaxray/markpdf#30]
Hi,

The package was working fine, until today... Some of the PDF's can't be handled because i get this error message:

Output:\n================\nERROR: Failed to get PageCount of the source file. [File need to be decrypted first] \n\n\nError Output:\n================\n",

The PDF can be openend without password so i dont understand why it tells it has to be decrypted

**Comment by laraben** [comment]
This is not an issue related to markpdf

**Comment by ZainXiao** [comment]
I meet same question.How you fix it?Can you tell me?
