### ISSUE TITLE
File need to be decrypted first

### ISSUE THREAD

**Issue by ZainXiao** [ajaxray/markpdf#37]
`
markpdf "/data/app/nyns_front_uc/storage/app/public/attachments/68289af0f229e078daf56e6592e47651.pdf" "/data/app/nyns_front_uc/storage/tmp/68289af0f229e078daf56e6592e4765193.png" "/data/app/nyns_front_uc/storage/myoutputtest.pdf" --tiles --angle=45 --spacing=30 -v
2024/10/16 15:30:59 Input PDF: /data/app/nyns_front_uc/storage/app/public/attachments/68289af0f229e078daf56e6592e47651.pdf
2024/10/16 15:30:59 Watermark Image: /data/app/nyns_front_uc/storage/tmp/68289af0f229e078daf56e6592e4765193.png
[DEBUG]  parser.go:1530 Pdf version 1.7
ERROR: Failed to get PageCount of the source file. [File need to be decrypted first] 
`
Some Pdf cannot be handle.They can be open without password or else.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by shirishbendre** [comment]
I have the same issue. I am running a much simpler command. 
If I don't get any response, I must move to another solution.

**Comment by ajaxray** [comment]
> I have the same issue. I am running a much simpler command. 
> 
> If I don't get any response, I must move to another solution.

Can you please share your command and a sample pdf that has the same issue? That'll help a lot to reproduce and debug the problem.

**Comment by shirishbendre** [comment]
Hi ajaxray,
I realized that this does not work for PDFs marked as secured. Thanks.

**Comment by ajaxray** [comment]
Got it. Thanks for sharing your findings @shirishbendre and @ZainXiao  . ❤️ 
I am going to add a note about this limitation.
