### ISSUE TITLE
Text Opacity not working like image opacity.

### ISSUE THREAD

**Issue by purohitvijay** [ajaxray/markpdf#5]
Hello @ajaxray ,

I'm using the command "**markpdf "test_text.pdf" "Approved, Not published" "/var/www/html/test_text_out.pdf" -c -s 20.0 -a 45 -o 0.5**" for add text as watermark, but the watermark is very dark. I also change **opacity 0.1** but in both cases, the watermark looks the same.
[test_text.pdf](https://github.com/ajaxray/markpdf/files/4040463/test_text.pdf)

But in the case of an image it's work fine.

Thank You In advance

**Comment by purohitvijay** [comment]
Hello @ajaxray,

Any Update on this.

Thank You.

**Comment by purohitvijay** [comment]
Hello @ajaxray 

Please guide me on that.

Thank You.

**Comment by ajaxray** [comment]
Hello @purohitvijay,

Sorry for very very late reply.

Actually, Text opacity is not yet implemented.  
If you check the [Roadmaps](https://github.com/ajaxray/markpdf#roadmap) of readme, it's mentioned there as a future plan.

Sorry again for failing to reply on time :(
