### ISSUE TITLE
How to add new line in text placeholder?

### ISSUE THREAD

**Issue by booleentech** [ajaxray/markpdf#7]
I am trying to add 2 lines(rows or line break) placeholder. I am using php to call command and trying to add new line "\n".

It gives no error and also no placeholder added in pdf. If I remove new line chars it works but in one line.

Is there any way I can add 2 lines as text placeholder?

**Comment by ajaxray** [comment]
Hello @booleentech ,

For writing in 2 lines, you can simply run 2 commands with same x position and adjusting y position.
```
markpdf "source.pdf" "The First Line" "output_tmp.pdf" -x -20 -y 20
markpdf "output_tmp.pdf" "The Second Line" "output_final.pdf" -x -20 -y 40
```

**Comment by booleentech** [comment]
Worked. Thanks.
