### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by Resurg3nt** [ajaxray/markpdf#8]
Hi,

You state that this is open source, but when I compiled this it required a unidoc dependency from Github. Although your built binaries work fine, when I compile it now, a watermark is added to the file from Unidoc and a license error is thrown.

I was trying to introduce a configuration option so that the watermark was only applied to the first page, but now this isn't possible.

Is this something you can revise?

**Comment by ajaxray** [comment]
Hello @Resurg3nt,

Thanks a lot for reporting!
Maybe unidoc have changed some licence terms of lately. 
I'll check which specific version will help to compile and works without watermark.

**Comment by ajaxray** [comment]
Hello @Resurg3nt ,

The issue has been solved by merging PR #12 

I am closing the issue now.
Please check and reopen if you still see the unwanted watermark and the Unidoc license error.

**Comment by tcastelly** [comment]
Hello @ajaxray ,

I'm trying to compile and use your application and it works. But if I update the "unidoc" I've an issue with a licence. I guess I don't have to update the library. I just wanted to let you know.
